-- Support tickets logged from the SkyBook bubble (assets/js/skybook-support.js).
-- booking-api records each ticket here, keeps its screenshot in the private
-- support-tickets bucket, and emails it to Aero Digital support. Reporter
-- details are copied from the signed-in staff profile at the time of logging.
-- Tickets are numbered from 1001 and shown as TKT-1001. Idempotent.

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity (start with 1001) unique,
  category text not null default 'problem' check (category in ('problem','question','idea')),
  message text not null check (length(btrim(message)) > 0),
  status text not null default 'open' check (status in ('open','in_progress','resolved','closed')),
  reporter_id uuid references auth.users(id) on delete set null,
  reporter_name text,
  reporter_username text,
  reporter_role text,
  reporter_email text,
  page_url text,
  page_title text,
  page_view text,
  context jsonb not null default '{}'::jsonb,
  screenshot_path text,
  email_status text not null default 'pending' check (email_status in ('pending','sent','failed')),
  email_id text,
  email_error text,
  emailed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists support_tickets_created_at_idx on public.support_tickets (created_at desc);
create index if not exists support_tickets_reporter_idx on public.support_tickets (reporter_id, created_at desc);

comment on table public.support_tickets is
  'Tickets logged from the SkyBook support bubble: message, page context and screenshot path. Emailed to Aero Digital support by booking-api.';

alter table public.support_tickets enable row level security;

drop policy if exists "admins read support tickets" on public.support_tickets;
create policy "admins read support tickets" on public.support_tickets
  for select using (public.is_booking_admin());

-- Screenshots can show guest names and payment details, so the bucket is private:
-- only the service role (booking-api) writes, and only SkyBook admins can read.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'support-tickets',
  'support-tickets',
  false,
  10485760,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "admins read support ticket screenshots" on storage.objects;
create policy "admins read support ticket screenshots"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'support-tickets'
  and public.is_booking_admin()
);
